// <auto-generated />
using System;
using Aguhon.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aguhon.Infrastructure.Migrations
{
    [DbContext(typeof(AguhonDbContext))]
    [Migration("20260628030736_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aguhon.Domain.Entities.CompendiumEntry", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("CreatureSpeciesId")
                        .HasColumnType("integer");

                    b.Property<bool>("Caught")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FirstCaughtAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FirstSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Seen")
                        .HasColumnType("boolean");

                    b.Property<int>("TimesCaught")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "CreatureSpeciesId");

                    b.HasIndex("CreatureSpeciesId");

                    b.HasIndex("PlayerId");

                    b.ToTable("CompendiumEntries");
                });

            modelBuilder.Entity("Aguhon.Domain.Entities.CreatureMove", b =>
                {
                    b.Property<int>("CreatureSpeciesId")
                        .HasColumnType("integer");

                    b.Property<int>("MoveId")
                        .HasColumnType("integer");

                    b.Property<int>("LearnAtLevel")
                        .HasColumnType("integer");

                    b.HasKey("CreatureSpeciesId", "MoveId");

                    b.HasIndex("MoveId");

                    b.ToTable("CreatureMoves");
                });

            modelBuilder.Entity("Aguhon.Domain.Entities.CreatureSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseAttack")
                        .HasColumnType("integer");

                    b.Property<float>("BaseCaptureRate")
                        .HasColumnType("real");

                    b.Property<int>("BaseDefense")
                        .HasColumnType("integer");

                    b.Property<int>("BaseHP")
                        .HasColumnType("integer");

                    b.Property<int>("BaseMana")
                        .HasColumnType("integer");

                    b.Property<int>("BaseSpecialAttack")
                        .HasColumnType("integer");

                    b.Property<int>("BaseSpecialDefense")
                        .HasColumnType("integer");

                    b.Property<int>("BaseSpeed")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFinalBoss")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMythic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStarter")
                        .HasColumnType("boolean");

                    b.Property<string>("LoreText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxEncounterLevel")
                        .HasColumnType("integer");

                    b.Property<int>("MinEncounterLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondaryType")
                        .HasColumnType("text");

                    b.Property<string>("SpriteUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CreatureSpecies");
                });

            modelBuilder.Entity("Aguhon.Domain.Entities.DefeatedTrainer", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("NpcTrainerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DefeatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PlayerId", "NpcTrainerId");

                    b.HasIndex("NpcTrainerId");

                    b.ToTable("DefeatedTrainers");
                });

            modelBuilder.Entity("Aguhon.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("CaptureTierMultiplier")
                        .HasColumnType("real");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CuresCondition")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HealAmount")
                        .HasColumnType("integer");

                    b.Property<float>("LumiwalosBonusMultiplier")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Aguhon.Domain.Entities.Move", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("BaseAccuracy")
                        .HasColumnType("real");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("ConditionChance")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InflictsCondition")
                        .HasColumnType("text");

                    b.Property<int>("ManaCost")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Power")
                        .HasColumnType("integer");

                    b.Property<bool>("StatStageAppliesToSelf")
                        .HasColumnType("boolean");

                    b.Property<int>("StatStageDelta")
                        .HasColumnType("integer");

                    b.Property<string>("StatStageTarget")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("Aguhon.Domain.Entities.NpcTrainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BadgeIndex")
                        .HasColumnType("integer");

                    b.Property<int>("GridX")
                        .HasColumnType("integer");

                    b.Property<int>("GridY")
                        .HasColumnType("integer");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.ToTable("NpcTrainers");
                });

            modelBuilder.Entity("Aguhon.Domain.Entities.NpcTrainerCreature", b =>
                {
                    b.Property<int>("NpcTrainerId")
                        .HasColumnType("integer");

                    b.Property<int>("CreatureSpeciesId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamSlot")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("NpcTrainerId", "CreatureSpeciesId", "TeamSlot");

                    b.HasIndex("CreatureSpeciesId");

                    b.ToTable("NpcTrainerCreatures");
                });

            modelBuilder.Entity("Aguhon.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableStatPoints")
                        .HasColumnType("integer");

                    b.Property<int>("BadgesEarned")
                        .HasColumnType("integer");

                    b.Property<int>("Bilis")
                        .HasColumnType("integer");

                    b.Property<string>("CurrentMapId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CurrentXP")
                        .HasColumnType("integer");

                    b.Property<int>("Diwa")
                        .HasColumnType("integer");

                    b.Property<int>("Lakas")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Loob")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlayerGridX")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerGridY")
                        .HasColumnType("integer");

                    b.Property<int>("Tibay")
                        .HasColumnType("integer");

                    b.Property<int>("XPToNextLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Aguhon.Domain.Entities.PlayerCreature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatureSpeciesId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentHP")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentMana")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("RosterSlot")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatureSpeciesId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCreatures");
                });

            modelBuilder.Entity("Aguhon.Domain.Entities.PlayerItem", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("PlayerItems");
                });

            modelBuilder.Entity("Aguhon.Domain.Entities.TypeEffectivenessEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttackingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefendingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Multiplier")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("TypeEffectivenessEntries");
                });

            modelBuilder.Entity("Aguhon.Domain.Entities.CompendiumEntry", b =>
                {
                    b.HasOne("Aguhon.Domain.Entities.CreatureSpecies", "Species")
                        .WithMany()
                        .HasForeignKey("CreatureSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aguhon.Domain.Entities.Player", "Player")
                        .WithMany("Compendium")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Aguhon.Domain.Entities.CreatureMove", b =>
                {
                    b.HasOne("Aguhon.Domain.Entities.CreatureSpecies", "CreatureSpecies")
                        .WithMany("CreatureMoves")
                        .HasForeignKey("CreatureSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aguhon.Domain.Entities.Move", "Move")
                        .WithMany("CreatureMoves")
                        .HasForeignKey("MoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatureSpecies");

                    b.Navigation("Move");
                });

            modelBuilder.Entity("Aguhon.Domain.Entities.DefeatedTrainer", b =>
                {
                    b.HasOne("Aguhon.Domain.Entities.NpcTrainer", "Trainer")
                        .WithMany()
                        .HasForeignKey("NpcTrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aguhon.Domain.Entities.Player", "Player")
                        .WithMany("DefeatedTrainers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Aguhon.Domain.Entities.NpcTrainerCreature", b =>
                {
                    b.HasOne("Aguhon.Domain.Entities.CreatureSpecies", "Species")
                        .WithMany()
                        .HasForeignKey("CreatureSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aguhon.Domain.Entities.NpcTrainer", "Trainer")
                        .WithMany("Creatures")
                        .HasForeignKey("NpcTrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Aguhon.Domain.Entities.PlayerCreature", b =>
                {
                    b.HasOne("Aguhon.Domain.Entities.CreatureSpecies", "Species")
                        .WithMany()
                        .HasForeignKey("CreatureSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aguhon.Domain.Entities.Player", "Player")
                        .WithMany("Roster")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Aguhon.Domain.Entities.PlayerItem", b =>
                {
                    b.HasOne("Aguhon.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aguhon.Domain.Entities.Player", "Player")
                        .WithMany("Inventory")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Aguhon.Domain.Entities.CreatureSpecies", b =>
                {
                    b.Navigation("CreatureMoves");
                });

            modelBuilder.Entity("Aguhon.Domain.Entities.Move", b =>
                {
                    b.Navigation("CreatureMoves");
                });

            modelBuilder.Entity("Aguhon.Domain.Entities.NpcTrainer", b =>
                {
                    b.Navigation("Creatures");
                });

            modelBuilder.Entity("Aguhon.Domain.Entities.Player", b =>
                {
                    b.Navigation("Compendium");

                    b.Navigation("DefeatedTrainers");

                    b.Navigation("Inventory");

                    b.Navigation("Roster");
                });
#pragma warning restore 612, 618
        }
    }
}
